---
# file: tasks/extract_resources.yml
- package:
    name: python-pip
    state: present

- pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - pexpect

- become: no
  find:
    path: "{{ mangos_directory }}/run/bin/tools"
    recurse: yes
    file_type: file
  register: find_result

- become: no
  copy:
    src: "{{ item.path }}"
    dest: "{{ wow_directory }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
    - "{{ find_result.files }}"

- become: no
  find:
    path: "{{ mangos_directory }}/contrib/extractor_scripts"
    recurse: yes
    file_type: file
  register: find_result

- become: no
  copy:
    src: "{{ item.path }}"
    dest: "{{ wow_directory }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
    - "{{ find_result.files }}"

- become: no
  file:
    dest: "{{ wow_directory }}/ExtractResources.sh"
    mode: a+x

#- become: no
#  expect:
#    command: "./ExtractResources.sh a"
#    responses:
#      "How many CPUs should be used for extracting mmaps?.*": 4
#  args:
#    chdir: "{{ wow_directory }}"

- become: no
  command: "cp -r {{ wow_directory | regex_replace(' ', '\\ ') }}/{{ item }} ."
  args:
    chdir: "{{ mangos_directory }}/run"
  with_items:
    - dbc
    - maps
    - mmaps
    - vmaps
