---
# file: tasks/extract_resources.yml
- become: no
  find:
    path: "{{ mangos_directory }}/run/bin/tools"
    recurse: yes
    file_type: file
  register: find_result

- become: no
  copy:
    src: "{{ item.path }}"
    dest: "{{ wow_directory }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
    - "{{ find_result.files }}"

- become: no
  find:
    path: "{{ mangos_directory }}/contrib/extractor_scripts"
    recurse: yes
    file_type: file
  register: find_result

- become: no
  copy:
    src: "{{ item.path }}"
    dest: "{{ wow_directory }}"
    mode: "{{ item.mode }}"
    remote_src: yes
  with_items:
    - "{{ find_result.files }}"

- become: no
  file:
    dest: "{{ wow_directory }}/ExtractResources.sh"
    mode: a+x

- become: no
  command: echo -e "4" | ./ExtractResources.sh a
  args:
    chdir: "{{ wow_directory }}"

- become: no
  command: "cp -r {{ wow_directory }}/{{ item }} ."
  args:
    chdir: "{{ mangos_directory }}/run"
  with_items:
    - dbc
    - maps
    - mmaps
    - vmaps
