---
# file: tasks/initialize_database
- mysql_db:
    name: all
    state: import
    target: "{{ mangos_directory }}/sql/create/db_drop_mysql.sql"
    single_transaction: yes
  ignore_errors: true

- mysql_db:
    name: all
    state: import
    target: "{{ mangos_directory }}/sql/create/db_create_mysql.sql"
    single_transaction: yes

- mysql_db:
    name: "{{ mangos_database_name }}"
    state: import
    target: "{{ mangos_directory }}/sql/base/mangos.sql"

- find:
    paths: "{{ mangos_directory }}/sql/base/dbc"
    recurse: yes
    patterns: "*.sql"
  register: find_result

- mysql_db:
    name: "{{ mangos_database_name }}"
    state: import
    target: "{{ item.path }}"
  with_items: "{{ find_result.files }}"

- mysql_db:
    name: "{{ characters_database_name }}"
    state: import
    target: "{{ mangos_directory }}/sql/base/characters.sql"

- mysql_db:
    name: "{{ realmd_database_name }}"
    state: import
    target: "{{ mangos_directory }}/sql/base/realmd.sql"

- stat:
    path: "{{ db_directory }}/InstallFullDB.config"
  register: stat_result

- command: ./InstallFullDB.sh
  args:
    chdir: "{{ db_directory }}"
  become: no
  when: stat_result is not defined or stat_result.stat.exists == false

- command: ./InstallFullDB.sh
  args:
    chdir: "{{ db_directory }}"
  become: no

- mysql_db:
    name: "{{ mangos_database_name }}"
    state: import
    target: "{{ mangos_directory}}/sql/scriptdev2/scriptdev2.sql"
